name: isolate_manager
description: Create long-lived isolates for single or multiple functions, with support for Web Workers (via an efficient generator) and WASM compilation.
version: 6.0.0+1
homepage: https://github.com/lamnhan066/isolate_manager/

topics:
  - isolate
  - worker
  - concurrent
  - pool

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.0.0
  stream_channel: ^2.0.0
  web: ^1.0.0

dev_dependencies:
  coverage: ^1.10.0
  isolate_manager_generator: ^0.0.12
  test: ^1.25.8
  very_good_analysis: ^6.0.0
