name: isolate_manager
description: An easy way to create multiple isolates for a function, also keep it active to send and receive data multiple times (also supports Worker on Web).
version: 4.0.0-rc.1
homepage: https://github.com/vnniz/isolate_manager

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  isolate_contactor: ^4.0.0-rc.1

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.0
  js: ^0.6.4
